In [3]:
import pandas as pd 
import numpy as np
import seaborn as sns

In [15]:
!pip install seaborn
sns.get_dataset_names()

Requirement already satisfied: seaborn in c:\users\sonam\anaconda3\lib\site-packages (0.13.2)
Requirement already satisfied: numpy!=1.24.0,>=1.20 in c:\users\sonam\anaconda3\lib\site-packages (from seaborn) (2.3.5)
Requirement already satisfied: pandas>=1.2 in c:\users\sonam\anaconda3\lib\site-packages (from seaborn) (3.0.3)
Requirement already satisfied: matplotlib!=3.6.1,>=3.4 in c:\users\sonam\anaconda3\lib\site-packages (from seaborn) (3.11.0)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\sonam\anaconda3\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\users\sonam\anaconda3\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\sonam\anaconda3\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (4.51.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\sonam\anaconda3\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.4.4)
Requirement already satisfied: packaging>=20.0 in c:\users\sonam\anaconda3\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (23.2)
Requirement already satisfied: pillow>=9 in c:\users\sonam\anaconda3\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (12.3.0)
Requirement already satisfied: pyparsing>=3 in c:\users\sonam\anaconda3\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (3.0.9)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\sonam\anaconda3\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\sonam\anaconda3\lib\site-packages (from pandas>=1.2->seaborn) (2023.3)
Requirement already satisfied: six>=1.5 in c:\users\sonam\anaconda3\lib\site-packages (from python-dateutil>=2.7->matplotlib!=3.6.1,>=3.4->seaborn) (1.16.0)

['anagrams',
 'anscombe',
 'attention',
 'brain_networks',
 'car_crashes',
 'diamonds',
 'dots',
 'dowjones',
 'exercise',
 'flights',
 'fmri',
 'geyser',
 'glue',
 'healthexp',
 'iris',
 'mpg',
 'penguins',
 'planets',
 'seaice',
 'taxis',
 'tips',
 'titanic']

In [18]:
df= sns.load_dataset("titanic")
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [24]:
df.shape

(891, 15)

In [28]:
df.isnull().sum()

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [30]:
(688/891)*100

77.21661054994388

In [34]:
del df["deck"]

In [22]:
df["age"].mean()

np.float64(29.69911764705882)

In [36]:
df["age"].median()

np.float64(28.0)

In [38]:
df["age"] = df["age"].fillna(28.0)

In [40]:
df=df.dropna()

In [46]:
df.duplicated().sum()

np.int64(116)

In [50]:
df.drop_duplicates(inplace=True)

In [52]:
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,Southampton,no,True

In [58]:
df["age"] = df["age"].astype(int)

In [60]:
df.info()

<class 'pandas.DataFrame'>
Index: 773 entries, 0 to 890
Data columns (total 14 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     773 non-null    int64
 1   pclass       773 non-null    int64
 2   sex          773 non-null    str
 3   age          773 non-null    int64
 4   sibsp        773 non-null    int64
 5   parch        773 non-null    int64
 6   fare         773 non-null    float64
 7   embarked     773 non-null    str
 8   class        773 non-null    category
 9   who          773 non-null    str
 10  adult_male   773 non-null    bool
 11  embark_town  773 non-null    str
 12  alive        773 non-null    str
 13  alone        773 non-null    bool
dtypes: bool(2), category(1), float64(1), int64(5), str(5)
memory usage: 74.9 KB

In [56]:
df["fare"] = df["fare"].round(2)

In [62]:
df["who"].value_counts()

who
man      443
woman    248
child     82
Name: count, dtype: int64

In [64]:
df.columns

Index(['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'class', 'who', 'adult_male', 'embark_town', 'alive',
       'alone'],
      dtype='str')

In [68]:
df=df.drop(columns=['alive','class','embarked'])

In [72]:
df.shape

(773, 11)

In [76]:
a1=pd.DataFrame ({"class":[1,2,3,1,2],"fare":["h","m","l","h","l"]})

In [78]:
a1

   class fare
0      1    h
1      2    m
2      3    l
3      1    h
4      2    l

In [86]:
#axis =1 is for columun ,for 0 is for rows.... by defualt is also for rows
a1.rename({'class':'Class'},axis=1)

   Class fare
0      1    h
1      2    m
2      3    l
3      1    h
4      2    l

In [88]:
a1.replace({"l":0,"m":1,"h":2})

   class fare
0      1    2
1      2    1
2      3    0
3      1    2
4      2    0

In [90]:
df = pd.DataFrame({
    "Emp_ID":[101,102,103,104,105,106,107,108,109,110],

    "Name":[
        " Mr. John Doe ",
        "Ms. Alice",
        "Mr. Bob",
        " Mrs. Emma ",
        "Dr. David",
        " Miss Sophia ",
        "Mr. James ",
        "Mr.Robert",
        " Mrs Olivia",
        "Dr. Henry "
    ],

    "Department":[
        "IT Dept",
        "HR Dept",
        "Finance Dept",
        "Sales Dept",
        "IT Dept",
        "HR Dept",
        "Finance Dept",
        "Sales Dept",
        "IT Dept",
        "HR Dept"
    ],

    "Email":[
        "john@gmail.com",
        "alice@yahoo.com",
        "bob@hotmail.com",
        "emma@gmail.com",
        "david@company.org",
        "sophia@yahoo.com",
        "james@gmail.com",
        "robert@company.org",
        "olivia@gmail.com",
        "henry@hotmail.com"
    ],

    "Phone":[
        "+91-9876543210",
        "+91-9123456789",
        "+91-9988776655",
        "+91-9871203456",
        "+91-9001122334",
        "+91-9012345678",
        "+91-9098765432",
        "+91-9988112233",
        "+91-9876001122",
        "+91-9898989898"
    ],

    "Salary":[
        "$50,000",
        "$45,500",
        "$60,200",
        "$48,700",
        "$75,000",
        "$55,400",
        "$82,500",
        "$46,900",
        "$65,000",
        "$90,000"
    ],

    "Location":[
        "Pune, Maharashtra",
        "Mumbai, Maharashtra",
        "Delhi, Delhi",
        "Bangalore, Karnataka",
        "Hyderabad, Telangana",
        "Pune, Maharashtra",
        "Mumbai, Maharashtra",
        "Delhi, Delhi",
        "Bangalore, Karnataka",
        "Hyderabad, Telangana"
    ],

    "Joining_Date":[
        "01-Jan-2024",
        "15-Feb-2023",
        "20-Mar-2022",
        "05-Apr-2021",
        "18-May-2020",
        "12-Jun-2024",
        "30-Jul-2023",
        "22-Aug-2022",
        "09-Sep-2021",
        "14-Oct-2020"
    ]
})

df

,Emp_ID,Name,Department,Email,Phone,Salary,Location,Joining_Date
0,101,Mr. John Doe,IT Dept,john@gmail.com,+91-9876543210,"$50,000","Pune, Maharashtra",01-Jan-2024
1,102,Ms. Alice,HR Dept,alice@yahoo.com,+91-9123456789,"$45,500","Mumbai, Maharashtra",15-Feb-2023
2,103,Mr. Bob,Finance Dept,bob@hotmail.com,+91-9988776655,"$60,200","Delhi, Delhi",20-Mar-2022
3,104,Mrs. Emma,Sales Dept,emma@gmail.com,+91-9871203456,"$48,700","Bangalore, Karnataka",05-Apr-2021
4,105,Dr. David,IT Dept,david@company.org,+91-9001122334,"$75,000","Hyderabad, Telangana",18-May-2020
5,106,Miss Sophia,HR Dept,sophia@yahoo.com,+91-9012345678,"$55,400","Pune, Maharashtra",12-Jun-2024
6,107,Mr. James,Finance Dept,james@gmail.com,+91-9098765432,"$82,500","Mumbai, Maharashtra",30-Jul-2023
7,108,Mr.Robert,Sales Dept,robert@company.org,+91-9988112233,"$46,900","Delhi, Delhi",22-Aug-2022
8,109,Mrs Olivia,IT Dept,olivia@gmail.com,+91-9876001122,"$65,000","Bangalore, Karnataka",09-Sep-2021
9,110,Dr. Henry,HR Dept,henry@hotmail.com,+91-9898989898,"$90,000","Hyderabad, Telangana",14-Oct-2020

In [92]:
a= "91-482354"
a.startswith("91-")

True

In [94]:
a="abc25@ltce.co.in"
a.endswith("@ltce.co.in")

True

In [96]:
a="91-992372"
a.split("-")

['91', '992372']

In [104]:
a="####$%#!abc@gmail.com#$%"
a.strip("#$%!")

'abc@gmail.com'

In [106]:
a.lstrip()

'####$%#!abc@gmail.com#$%'

In [108]:
a.rstrip()

'####$%#!abc@gmail.com#$%'

In [114]:
df["Name"].str.lstrip()

0    Mr. John Doe
1        Ms. Alice
2          Mr. Bob
3       Mrs. Emma
4        Dr. David
5     Miss Sophia
6       Mr. James
7        Mr.Robert
8       Mrs Olivia
9       Dr. Henry
Name: Name, dtype: str

In [116]:
df["Name"].str.removeprefix("Mr.")

0     Mr. John Doe
1         Ms. Alice
2               Bob
3        Mrs. Emma
4         Dr. David
5      Miss Sophia
6            James
7            Robert
8        Mrs Olivia
9        Dr. Henry
Name: Name, dtype: str

In [132]:
df["Department"].str.removesuffix("Dept")

0         IT
1         HR
2    Finance
3      Sales
4         IT
5         HR
6    Finance
7      Sales
8         IT
9         HR
Name: Department, dtype: str

In [126]:
df["Phone"].str.replace("+91-","",regex=False)

0    9876543210
1    9123456789
2    9988776655
3    9871203456
4    9001122334
5    9012345678
6    9098765432
7    9988112233
8    9876001122
9    9898989898
Name: Phone, dtype: str

In [128]:
df["Salary"].str.replace("$","",regex=False)

0    50,000
1    45,500
2    60,200
3    48,700
4    75,000
5    55,400
6    82,500
7    46,900
8    65,000
9    90,000
Name: Salary, dtype: str

In [130]:
df["Salary"].str.replace(",","",regex=False)

0    $50000
1    $45500
2    $60200
3    $48700
4    $75000
5    $55400
6    $82500
7    $46900
8    $65000
9    $90000
Name: Salary, dtype: str

In [134]:
df["Location"].str.split(",")

0       [Pune,  Maharashtra]
1     [Mumbai,  Maharashtra]
2            [Delhi,  Delhi]
3    [Bangalore,  Karnataka]
4    [Hyderabad,  Telangana]
5       [Pune,  Maharashtra]
6     [Mumbai,  Maharashtra]
7            [Delhi,  Delhi]
8    [Bangalore,  Karnataka]
9    [Hyderabad,  Telangana]
Name: Location, dtype: object

In [142]:
df["DateTime"]=pd.Timestamp.now()
print(df)

   Emp_ID            Name    Department               Email           Phone  \
0     101   Mr. John Doe        IT Dept      john@gmail.com  +91-9876543210
1     102       Ms. Alice       HR Dept     alice@yahoo.com  +91-9123456789
2     103         Mr. Bob  Finance Dept     bob@hotmail.com  +91-9988776655
3     104      Mrs. Emma     Sales Dept      emma@gmail.com  +91-9871203456
4     105       Dr. David       IT Dept   david@company.org  +91-9001122334
5     106    Miss Sophia        HR Dept    sophia@yahoo.com  +91-9012345678
6     107      Mr. James   Finance Dept     james@gmail.com  +91-9098765432
7     108       Mr.Robert    Sales Dept  robert@company.org  +91-9988112233
8     109      Mrs Olivia       IT Dept    olivia@gmail.com  +91-9876001122
9     110      Dr. Henry        HR Dept   henry@hotmail.com  +91-9898989898

    Salary              Location Joining_Date                   DateTime
0  $50,000     Pune, Maharashtra  01-Jan-2024 2026-08-13 15:35:24.109084
1  $45,500   Mumbai, Maharashtra  15-Feb-2023 2026-08-13 15:35:24.109084
2  $60,200          Delhi, Delhi  20-Mar-2022 2026-08-13 15:35:24.109084
3  $48,700  Bangalore, Karnataka  05-Apr-2021 2026-08-13 15:35:24.109084
4  $75,000  Hyderabad, Telangana  18-May-2020 2026-08-13 15:35:24.109084
5  $55,400     Pune, Maharashtra  12-Jun-2024 2026-08-13 15:35:24.109084
6  $82,500   Mumbai, Maharashtra  30-Jul-2023 2026-08-13 15:35:24.109084
7  $46,900          Delhi, Delhi  22-Aug-2022 2026-08-13 15:35:24.109084
8  $65,000  Bangalore, Karnataka  09-Sep-2021 2026-08-13 15:35:24.109084
9  $90,000  Hyderabad, Telangana  14-Oct-2020 2026-08-13 15:35:24.109084

In [158]:
df["DateTime"] = pd.to_datetime(df["DateTime"])

In [162]:
df["year"]=df["DateTime"].dt.year
df["Month"]=df["DateTime"].dt.month
df["Day"]=df["DateTime"].dt.day

In [168]:
df["Day_Name"]=df["DateTime"].dt.day_name()
df["Month_Name"]=df["DateTime"].dt.month_name()
df.head()

,Emp_ID,Name,Department,Email,Phone,Salary,Location,Joining_Date,DateTime,year,Month,Day,Day_Name,Month_Name
0,101,Mr. John Doe,IT Dept,john@gmail.com,+91-9876543210,"$50,000","Pune, Maharashtra",01-Jan-2024,2026-08-13 15:35:24.109084,2026,8,13,Thursday,August
1,102,Ms. Alice,HR Dept,alice@yahoo.com,+91-9123456789,"$45,500","Mumbai, Maharashtra",15-Feb-2023,2026-08-13 15:35:24.109084,2026,8,13,Thursday,August
2,103,Mr. Bob,Finance Dept,bob@hotmail.com,+91-9988776655,"$60,200","Delhi, Delhi",20-Mar-2022,2026-08-13 15:35:24.109084,2026,8,13,Thursday,August
3,104,Mrs. Emma,Sales Dept,emma@gmail.com,+91-9871203456,"$48,700","Bangalore, Karnataka",05-Apr-2021,2026-08-13 15:35:24.109084,2026,8,13,Thursday,August
4,105,Dr. David,IT Dept,david@company.org,+91-9001122334,"$75,000","Hyderabad, Telangana",18-May-2020,2026-08-13 15:35:24.109084,2026,8,13,Thursday,August

In [170]:
df["Time"]=df["DateTime"].dt.time