<a href="https://colab.research.google.com/github/sonam2006-sandanshiv/microsoft-workshop/blob/main/13_08_26.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
a1=df= pd.DataFrame({
    "Name":["john","Alice","Bob"],
    "Marks":[40,30,20]
})

In [ ]:
a1

    Name  Marks
0   john     40
1  Alice     30
2    Bob     20

In [ ]:
a1["Grade"]=["O","A","B"]
a1.sort_values("Marks")

    Name  Marks Grade
2    Bob     20     B
1  Alice     30     A
0   john     40     O

In [ ]:
a1.sort_values("Marks",ascending=False)

    Name  Marks Grade
0   john     40     O
1  Alice     30     A
2    Bob     20     B

In [ ]:
a1.sort_values("Name")

    Name  Marks Grade
1  Alice     30     A
2    Bob     20     B
0   john     40     O

In [ ]:
a1[["Name","Marks"]]

    Name  Marks
0   john     40
1  Alice     30
2    Bob     20

In [ ]:
df=pd.read_csv("/content/clientes (2).csv")

In [ ]:
df.head()

,cod_cliente,sexo,estado_civil,dependentes,educacao,empregado,renda,renda_conjuge,emprestimo,prestacao_mensal,historico_credito,imovel,aprovacao_emprestimo
0,LP001002,Male,No,0,Graduate,No,5849,0,NaN,360.0,1.0,Urban,Y
1,LP001003,Male,Yes,1,Graduate,No,4583,1508,128.0,360.0,1.0,Rural,N
2,LP001005,Male,Yes,0,Graduate,Yes,3000,0,66.0,360.0,1.0,Urban,Y
3,LP001006,Male,Yes,0,Not Graduate,No,2583,2358,120.0,360.0,1.0,Urban,Y
4,LP001008,Male,No,0,Graduate,No,6000,0,141.0,360.0,1.0,Urban,Y

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 614 entries, 0 to 613
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   cod_cliente           614 non-null    object
 1   sexo                  601 non-null    object
 2   estado_civil          611 non-null    object
 3   dependentes           599 non-null    object
 4   educacao              614 non-null    object
 5   empregado             582 non-null    object
 6   renda                 614 non-null    int64
 7   renda_conjuge         614 non-null    object
 8   emprestimo            592 non-null    float64
 9   prestacao_mensal      600 non-null    float64
 10  historico_credito     564 non-null    float64
 11  imovel                614 non-null    object
 12  aprovacao_emprestimo  614 non-null    object
dtypes: float64(3), int64(1), object(9)
memory usage: 62.5+ KB

In [ ]:
df["sexo"]=df["sexo"].fillna("Male")

In [ ]:
df["dependentes"].mode()

0    0
Name: dependentes, dtype: object

In [ ]:
df["dependentes"].value_counts()

dependentes
0     345
1     102
2     101
3+     51
Name: count, dtype: int64

In [ ]:
df["dependentes"]=df["dependentes"].fillna(0)

In [ ]:
df["historico_credito"]=df["historico_credito"].fillna(0)

In [ ]:
df["emprestimo"].median(0)

128.0

In [ ]:
df["emprestimo"]=df["emprestimo"].fillna(128.0)

In [ ]:
df["empregado"].mode()

0    No
Name: empregado, dtype: object

In [ ]:
df["empregado"]=df["empregado"].fillna("No")

In [ ]:
df["estado_civil"].mode()

0    Yes
Name: estado_civil, dtype: object

In [ ]:
df["estado_civil"]=df["estado_civil"].fillna("No")

In [ ]:
df["prestacao_mensal"].median()

360.0

In [ ]:
df["prestacao_mensal"]=df["prestacao_mensal"].fillna(360.0)

In [ ]:
df.isnull().sum()

cod_cliente             0
sexo                    0
estado_civil            0
dependentes             0
educacao                0
empregado               0
renda                   0
renda_conjuge           0
emprestimo              0
prestacao_mensal        0
historico_credito       0
imovel                  0
aprovacao_emprestimo    0
dtype: int64

In [ ]:
del df ["cod_cliente"]

In [ ]:
df.shape

(614, 12)

In [ ]:
df.head()

,sexo,estado_civil,dependentes,educacao,empregado,renda,renda_conjuge,emprestimo,prestacao_mensal,historico_credito,imovel,aprovacao_emprestimo
0,Male,No,0,Graduate,No,5849,0,128.0,360.0,1.0,Urban,Y
1,Male,Yes,1,Graduate,No,4583,1508,128.0,360.0,1.0,Rural,N
2,Male,Yes,0,Graduate,Yes,3000,0,66.0,360.0,1.0,Urban,Y
3,Male,Yes,0,Not Graduate,No,2583,2358,120.0,360.0,1.0,Urban,Y
4,Male,No,0,Graduate,No,6000,0,141.0,360.0,1.0,Urban,Y

In [ ]:
df["sexo"].value_counts()

sexo
Male      502
Female    112
Name: count, dtype: int64

In [ ]:
df["educacao"].value_counts()

educacao
Graduate        480
Not Graduate    134
Name: count, dtype: int64

In [ ]:
len(df.query(" sexo=='Male' and educacao=='Graduate' "))

388

In [ ]:
len(df.query(" imovel=='Urban' and aprovacao_emprestimo=='Y' and renda>=3000 "))

96

In [ ]:
#rent collected on the basis of
df.groupby("renda")["imovel"].min()

renda
150          Rural
210      Semiurban
416          Urban
645          Rural
674          Rural
           ...
39147    Semiurban
39999    Semiurban
51763        Urban
63337        Urban
81000        Rural
Name: imovel, Length: 505, dtype: object

In [ ]:
df.groupby('dependentes')["emprestimo"].sum().sort_values()

dependentes
0      1925.0
3+     9610.0
2     15106.0
1     16057.0
0     46794.0
Name: emprestimo, dtype: float64

In [ ]:
df.groupby('dependentes')["emprestimo"].sum().sort_values(ascending=False)

dependentes
0     46794.0
1     16057.0
2     15106.0
3+     9610.0
0      1925.0
Name: emprestimo, dtype: float64

In [ ]:
df.groupby('dependentes')["emprestimo"].sum().sort_values(ascending=False)[:2]

dependentes
0    46794.0
1    16057.0
Name: emprestimo, dtype: float64

In [ ]:
#pd.crosstab ,pd.pivot_table,np.isin,